name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd fastapi-app
            git pull
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker build -t fastapi-app .
            docker run -d -p 8000:8000 --name fastapi-app fastapi-app